env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
settings:
  import/resolver:
    alias:
      map:
        - - '@'
          - ./src
      extensions:
        - .js
        - .jsx
        - .json
rules:
  prettier/prettier: error
  no-restricted-exports:
    - error
    - restrictedNamedExports:
        - then
  react/react-in-jsx-scope: off
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/require-default-props: 0
  react/prop-types: 0
  react/jsx-props-no-spreading: 0
