env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
  - prettier
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
settings:
  import/resolver:
    alias:
      map:
        - - '@'
          - ./src
      extensions:
        - .js
        - .jsx
        - .json
rules:
  react/react-in-jsx-scope: off
  prettier/prettier: error
  no-restricted-exports:
    - error
    - restrictedNamedExports:
        - then
